# x =4 + 2

In [2]:
print(x)


6


In [1]:
x = 4 -2 


In [2]:
x


2

In [3]:
x = 4 * 2

In [4]:
x


8

In [5]:
x = 5 // 2

In [6]:
x


2

In [7]:
x= 5 / 2

In [8]:
x


2.5

In [9]:

speed = 25
time = 4
distance = speed * time
distance

100

In [3]:

Principal =5000
Rate = 10
Time = 4
SimpleInterest = ( Principal * Rate * Time ) // 100
int(SimpleInterest)

2000

In [6]:
Area_square = (4)**2

In [7]:
Area_square

16

In [8]:
print(1 + 2 ** 3 // 4 * 5)

11


In [9]:
my_name = "John"
age = 28
pi = 3.14

In [10]:
print(my_name)
print(pi)

John
3.14


In [14]:
bank_balance  = 200
bank_balance

200

In [18]:
x = 10

In [21]:
my_int = int(20)

In [22]:
my_float = 15.85

In [23]:
my_string  = 'Hello World'

In [24]:
my_bool  = True

In [37]:
height  =20
width = 80
area_of_rectangle = height * width

In [38]:
area_of_rectangle

1600

In [43]:
print("game" + 1)

TypeError: must be str, not int

In [44]:
total_interest = 9762.69

In [45]:
type(total_interest )

float

In [46]:
type(area_of_rectangle )

int

In [1]:
print(5 + 8)

13


In [2]:
print("John" + " " + "Barley")

John Barley


In [3]:
print("BMI is " + 25)

TypeError: must be str, not int

In [6]:
bmi = 25

print("BMI is ", + bmi)
bmi_str =str(bmi)

BMI is  25


In [14]:
message = "BMI is " + bmi_str

message

In [16]:
message

'BMI is 25'

In [30]:
first='Cloudx'
second='Lab'
final=first+second

In [31]:
final

'CloudxLab'

In [28]:
games = "football" + "basketball"

In [29]:
games

'footballbasketball'

In [42]:
games = "A" * 20

In [43]:
games

'AAAAAAAAAAAAAAAAAAAA'

In [46]:
animal = 'cat'

In [47]:
ten_animals = animal * 10

In [48]:
ten_animals

'catcatcatcatcatcatcatcatcatcat'

In [1]:
type(23)

int

In [36]:
def pay_calculator(hours,rate):

    print("hours:",hours)
    if hours <= 40:
        payment = hours*rate
    else:
        rpayment = 40*rate 
        cpayment = (hours - 40)* (rate *1.5)
        payment = rpayment + cpayment
    return payment
    
    
    

In [37]:
print(pay_calculator(45, 10))

hours: 45
475.0


In [41]:
print(max('Hello world'))

w


In [42]:
area_of_circle = 78.5

In [45]:
area_of_circle = str(area_of_circle)

In [46]:
area_of_circle_msg = "Area of the circle is - " + area_of_circle
print(area_of_circle_msg)

Area of the circle is - 78.5


In [52]:
len("cloudxlab")

9

In [54]:
max("cloudxlab")

'x'

In [55]:
min("cloudxlab")

'a'

In [57]:
square_area =8.9 * 8.9

In [67]:
square_area_type=type(square_area)

square_area_int=int(square_area)

square_area_str=str(square_area_int)

In [68]:
square_area_type

float

In [69]:
square_area_int

79

In [70]:
square_area_str

'79'

In [84]:
import math

In [85]:
math.log10(1000)

3.0

In [86]:
math.cos(0)

1.0

In [87]:
math.sqrt(4)

2.0

In [89]:
square_root= math.sqrt(56.98)

In [90]:
square_root

7.548509786706248

In [91]:
sin_rad=26*(math.pi/180)

In [92]:
sin_rad

0.4537856055185257

In [93]:
sin_degree=math.sin(sin_rad)

In [95]:
log_e=math.log(1000)
print(square_root)
print(sin_rad)
print(sin_degree)
print(log_e)

7.548509786706248
0.4537856055185257
0.4383711467890774
6.907755278982137


In [ ]:
import numpy as np

grid = [[5,3,0,0,7,0,0,0,0],
        [6,0,0,1,9,5,0,0,0],
        [0,9,8,0,0,0,0,6,0],
        [8,0,0,0,6,0,0,0,3],
        [4,0,0,8,0,3,0,0,1],
        [7,0,0,0,2,0,0,0,6],
        [0,6,0,0,0,0,2,8,0],
        [0,0,0,0,1,9,0,0,5],
        [0,0,0,0,0,0,0,0,0]]

def possible(row, column, number):
    global grid
    #Is the number appearing in the given row?
    for i in range(0,9):
        if grid[row][i] == number:
            return False

    #Is the number appearing in the given column?
    for i in range(0,9):
        if grid[i][column] == number:
            return False
    
    #Is the number appearing in the given square?
    x0 = (column // 3) * 3
    y0 = (row // 3) * 3
    for i in range(0,3):
        for j in range(0,3):
            if grid[y0+i][x0+j] == number:
                return False

    return True

def solve():
    global grid
    for row in range(0,9):
        for column in range(0,9):
            if grid[row][column] == 0:
                for number in range(1,10):
                    if possible(row, column, number):
                        grid[row][column] = number
                        solve()
                        grid[row][column] = 0
                return
      
    print(np.matrix(grid))

    input('More possible solutions')

solve()




[[5 3 4 6 7 8 1 9 2]
 [6 7 2 1 9 5 3 4 8]
 [1 9 8 3 4 2 5 6 7]
 [8 5 9 7 6 1 4 2 3]
 [4 2 6 8 5 3 9 7 1]
 [7 1 3 9 2 4 8 5 6]
 [9 6 1 5 3 7 2 8 4]
 [2 8 7 4 1 9 6 3 5]
 [3 4 5 2 8 6 7 1 9]]
More possible solutions2
[[5 3 4 6 7 8 9 1 2]
 [6 7 2 1 9 5 3 4 8]
 [1 9 8 3 4 2 5 6 7]
 [8 5 9 7 6 1 4 2 3]
 [4 2 6 8 5 3 7 9 1]
 [7 1 3 9 2 4 8 5 6]
 [9 6 1 5 3 7 2 8 4]
 [2 8 7 4 1 9 6 3 5]
 [3 4 5 2 8 6 1 7 9]]


In [12]:
import random
for i in range(0,10):
    print(i)
    random_number = random.random()
    print (random_number)
    random_int =int(random_number)
    print (random_int)
    print ("x" * 20)
    

0
0.7128229909162741
0
xxxxxxxxxxxxxxxxxxxx
1
0.8046148466730194
0
xxxxxxxxxxxxxxxxxxxx
2
0.8205230346360578
0
xxxxxxxxxxxxxxxxxxxx
3
0.5908823885803363
0
xxxxxxxxxxxxxxxxxxxx
4
0.8382319558938964
0
xxxxxxxxxxxxxxxxxxxx
5
0.1687652126421728
0
xxxxxxxxxxxxxxxxxxxx
6
0.4252883343178707
0
xxxxxxxxxxxxxxxxxxxx
7
0.22086950503479752
0
xxxxxxxxxxxxxxxxxxxx
8
0.009021669973651725
0
xxxxxxxxxxxxxxxxxxxx
9
0.009824247176546064
0
xxxxxxxxxxxxxxxxxxxx


In [22]:
name =input ("give the name :")
def print_name(name)  :
    
    return name 

give the name :xyz


In [24]:
print_name(name)

'xyz'

In [25]:
print(type(print_name))

<class 'function'>


In [3]:
def multiply(message, *args):
    output = 1
    for arg in args:
        output *= arg
    return message + " " + str(output)


In [4]:
multiply_value = multiply("My Sum:", 1, 2, 4, 6)
print(multiply_value)

My Sum: 48


In [5]:
def multiply(*args, message):
    output = 1
    for arg in args:
        output *= arg
    return message + " " + str(output)

In [6]:
multiply_value = multiply(1, 2, 4, 6, message="My Sum:")
print(multiply_value)

My Sum: 48


In [7]:
def multiply(premessage, *args, message):
    output = 1
    for arg in args:
        output *= arg
    return premessage + " " + str(output) + " " + message

In [8]:
multiply_value = multiply("Starting calculation:", 2, 4, 6, message="My Sum:")
print(multiply_value)

Starting calculation: 48 My Sum:


In [11]:
def groupdata(message, **kwargs):
    grouped_data ={}
    for key,value in kwargs.items():
        grouped_data[key.split("_")[0]] = grouped_data.get(key.split("_")[0], 0) + value
    return message + " " + str(grouped_data)



In [12]:
summary = groupdata(
    "My fruits:",
    apple_indian = 3,
    orange_indian = 5,
    apple_mexican = 6,
    orange_mexica = 7,
    banana=11
)
print(summary)

My fruits: {'apple': 9, 'orange': 12, 'banana': 11}


In [15]:
def my_function (number ):
    xyz = number
    xyz_str = str(xyz)
    xyz_str= xyz_str +"cloudxlab "
    print(xyz_str)
    

In [16]:
my_function (10 )

10cloudxlab 


In [19]:
def new_function (num):
    import math
    return math.pi * num
    

In [20]:
def void_function (num1,num2):
    print(new_function(num1**num2))

In [21]:
void_function(4.6, 7.3)

216412.35147094267


In [ ]:
inp = input()

In [ ]:
 name = input('What is Cloudxlab?\n')

In [3]:
question = 'What is 2 multiplied by 3?\n'
answer = input(question)
print(int(answer))

What is 2 multiplied by 3?
12
12


In [12]:
def input_name():
    subject = input("What am I studying ?")
    return subject

subject = input_name()
print(subject)

What am I studying ?Python
Python


In [18]:
#Caclulating and printing my age
current_year = input("current year:")
year_of_birth = input("Please enter Birth year")
age = int(current_year) - int(year_of_birth)
print(age)

current year:2024
Please enter Birth year1987
37


In [19]:
#Caclulating and printing my age
current_year = 2018
year_of_birth = 1990
age = current_year - year_of_birth
print(age)

28


In [20]:
#Caclulating and printing my age
current_year = 2018
year_of_birth = 1990
age = current_year - year_of_birth
print(age)

28


In [21]:
1 == 1

True

In [22]:
2 == 1

False

In [23]:
2 == 1


False

In [24]:
x != y               # x is not equal to y
x > y                # x is greater than y
x < y                # x is less than y
x >= y               # x is greater than or equal to y
x <= y               # x is less than or equal to y
x is y               # x is the same as y
x is not y           # x is not the same as y

NameError: name 'x' is not defined

In [13]:
def is_on_line(x1, x2, x):
    if x1 <= x <= x2:
        return True
    elif x2<= x <=x1:
        return True
    return False
    

In [14]:

is_on_line(10, 20, 30)


False

In [15]:
is_on_line(10, 20, 20)


True

In [16]:
is_on_line(10, 20, 20)


True

In [17]:
is_on_line(10, 20, -10)


False

In [18]:
is_on_line(-4, -5, -4.5)

True

In [19]:
type(is_on_line)

function

In [25]:
def conditional_statements(num1, num2, num3, num4):
    if num1<int(num2) and num1> num3 and num1==num4 :
        if  num3 < num1 and num3 < int(num2) and num3 < num4:
            if type(num2) is float:
                sum = num1+num2+num3+num4
                print(sum)
                
            else:
               # print("B")
                return None
        else:
            print("C")
            
    else:
        #print("D")
        return None

In [26]:
conditional_statements(13,11.05,10,13)

In [27]:
print(conditional_statements(1,2.3,0,4))

None


In [28]:
print(conditional_statements(1,2.3,0,1));

4.3
None


In [96]:
def except_func (num):
    try :
            mul = num * num
            return mul
            print (mul)
    except:
        return ('invalid number')


In [97]:
except_func(10)

100

In [98]:
except_func("sample")

'invalid number'

In [117]:
a = 0

a = a // 3

In [118]:
a

0

In [126]:
k = 0
for i in [9, 41, 12, 3, 74, 15] :
    if i > k :
        print("i",i,">k",k)
        k = i
print ("largest is: ",k)   

i 9 >k 0
i 41 >k 9
i 74 >k 41
largest is:  74


In [22]:
def print_even(n):
    for i in range (n):
        if i%2 == 0:
            print (i)
        
        

In [21]:
x =0%2
x

0

In [24]:
print_even(5)


0
2
4


In [ ]:
def binary_search(arr, target):
    low, high = 0, len(arr) - 1
    
    while low <= high:
        mid = (low + high) // 2
        
        if arr[mid] == target:
            return mid
        elif arr[mid] < target:
            low = mid + 1
        else:
            high = mid - 1
    
    return -1

# Example usage:
sorted_list = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
target_value = 7

result = binary_search(sorted_list, target_value)

if result != -1:
    print(f"Target {target_value} found at index {result}.")
else:
    print(f"Target {target_value} not found in the list.")
    

In [ ]:
#PALINDROME # ABCDCBA

In [12]:

def palin(str1,str2):
    for i in x:
        str2 = i + str2
        if (str1 == str2):
            print("Yes")
        else:
            print("No")

In [11]:
palin("aa","aa")

No
No
No
No
No
No
No


In [19]:


def palindrom_test(str):
    rev = reversed(str)  
    if list(str) == list(rev):
        print("PALINDROME !")  
    else:
        print("NOT PALINDROME !")  

In [22]:
palindrom_test('')

PALINDROME !


In [21]:
tests = {
    "ABCDCBA": True,
    "AA": True,
    "A": True,
    "": True,
    "AB": False,
    "ABCD": False,
    "ABBA": True,
    "abBA": False
}
def check_tests(f, tests):
    for k,v in tests.items():
        print("Checking...", k, v)
        if f(k) == v:
            print("PASSED")
        else:
            print("FAILED")

In [ ]:
def checkpalin(txt):
    arr =list(txt)
    ispalin = True
    for i in range (len(arr)/2):
        print (arr[i]+'<----->'+)
    

In [ ]:
def find1s(arr):
    for i in range(len(arr)):
        if arr[i] == 1:
            break
    return len(arr) -1

In [ ]:
assert(find1s([0,0,0,0,1,1,1])==3)

In [1]:
def find_one(arr):
    low =0
    high = len(arr)
    while low <= high:
        mid= (low +high)//2
        #have i found the position?
        if arr[mid] == 1 :
            #Found
            if mid>0 and arr [mid -1] ==0:
                break;
            else:
                high = mid-1
        else:
            low =mid +1
    if low <= high:
        return len(arr) - mid
    else :
        if arr[mid]==0:
            return 0
        else:
            return len(arr)

In [25]:
def compound_interest(principle, rate, years):
    interest = 0
    for i in range(years):
            print (i)
            if i < 1:
                interest = (principle * rate * years) / 100
                print("I",interest) 
            else:
                incprinciple = principle+interest
                interest =(incprinciple * rate * years) / 100
                total_acum_value = incprinciple + interest
                comp_interest = total_acum_value - principle
    
    return comp_interest

In [26]:
 compound_interest(100,5,2)

0
I 10.0
1


21.0

In [27]:
def compound_interest(principle, rate, years):
    si = 0
    principle1 = principle
    for i in range(years+1):
        if(i>0):
            principle1 = principle1 + si
            si = (principle1 * rate * 1)/100
    principle1 = principle1 + si
    comp_interest = principle1 - principle
    return(comp_interest)

In [28]:
 compound_interest(100,5,2)

10.25

In [89]:
def fact(n):
    list1 = []
    sum = 0
    for i in range(1,n+1):       
        if n % i == 0:            
            if i % 2 != 0:
                list1.append(i)               
    for i in list1:
        sum = sum + i
    return sum
    
    
    
def special_func (num):
    total = 0
    if  type(num) == int :
        if num >= 0 :
            result = fact(num)
            return result
        else:
            return -10
    else:
        return -10

In [88]:

def fact(n):
    list1 = []
    sum = 0
    for i in range(1,n+1):
        print ("i",i)
        if n % i == 0:
            print ("i--> factor:",i)
            if i % 2 != 0:
                list1.append(i)
                print ("list1",list1)
    for i in list1:
        sum = sum + i
    print("sum:",sum)                

In [90]:
 special_func(24)

4

In [160]:
def str_func (Input):
    lenin= len(str(Input))
    return  Input[lenin -1]

def sum_str_func(inp):
    inp = str(inp)
    number = str_func (inp)
    
    output= 0
    for i in  str(inp):
        output = output + int(i)
    return output
    

In [161]:
str_func ('cloudxlab')

'b'

In [162]:
sum_str_func(1234)

10

In [172]:
s = "cloudxlab"
print(s[1:5])
print(s[4:4])

loud



In [171]:
print(s[4:4])

In [173]:
print(s[-1])

b


In [174]:
print(s[-2])

a


In [177]:
print(s[:-2])

cloudxl


In [197]:

def slicing_func (input):
    s = input
    print(s[2:]) 

In [198]:
slicing_func("cloudxlab")


oudxlab


In [213]:
a = "Cloudxlab is a large ed-tech platform for ml and big data"
count = 0
for letter in a:
    
    if letter == 'l':
        print(letter)
        count = count + 1
        print(count)
count

l
1
l
2
l
3
l
4
l
5


5

In [207]:
result = 'cloud' in 'cloudxlab'
print (result)

True


In [208]:
string = "machine"
print (string == " machine")

False


In [214]:
a = "cloudxlab"
dir(a)

['__add__',
 '__class__',
 '__contains__',
 '__delattr__',
 '__dir__',
 '__doc__',
 '__eq__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__getitem__',
 '__getnewargs__',
 '__gt__',
 '__hash__',
 '__init__',
 '__init_subclass__',
 '__iter__',
 '__le__',
 '__len__',
 '__lt__',
 '__mod__',
 '__mul__',
 '__ne__',
 '__new__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__rmod__',
 '__rmul__',
 '__setattr__',
 '__sizeof__',
 '__str__',
 '__subclasshook__',
 'capitalize',
 'casefold',
 'center',
 'count',
 'encode',
 'endswith',
 'expandtabs',
 'find',
 'format',
 'format_map',
 'index',
 'isalnum',
 'isalpha',
 'isdecimal',
 'isdigit',
 'isidentifier',
 'islower',
 'isnumeric',
 'isprintable',
 'isspace',
 'istitle',
 'isupper',
 'join',
 'ljust',
 'lower',
 'lstrip',
 'maketrans',
 'partition',
 'replace',
 'rfind',
 'rindex',
 'rjust',
 'rpartition',
 'rsplit',
 'rstrip',
 'split',
 'splitlines',
 'startswith',
 'strip',
 'swapcase',
 'title',
 'translate',
 'upper',
 'zfill']

In [215]:
help(a.translate)

Help on built-in function translate:

translate(...) method of builtins.str instance
    S.translate(table) -> str
    
    Return a copy of the string S in which each character has been mapped
    through the given translation table. The table must implement
    lookup/indexing via __getitem__, for instance a dictionary or list,
    mapping Unicode ordinals to Unicode ordinals, strings, or None. If
    this operation raises LookupError, the character is left untouched.
    Characters mapped to None are deleted.



In [216]:
help(str.translate)

Help on method_descriptor:

translate(...)
    S.translate(table) -> str
    
    Return a copy of the string S in which each character has been mapped
    through the given translation table. The table must implement
    lookup/indexing via __getitem__, for instance a dictionary or list,
    mapping Unicode ordinals to Unicode ordinals, strings, or None. If
    this operation raises LookupError, the character is left untouched.
    Characters mapped to None are deleted.



In [217]:
print(a.upper())

CLOUDXLAB


In [218]:
print(a)

cloudxlab


In [219]:
data1 = "someone@gmail.com"

In [223]:
position = data1.find('@gmail')
position

7

In [226]:
position = data1.find('@gmail', 4, 6)
position

-1

In [227]:
a = [12, 3.4, 34, 'cloudxlab', [2.3, 1.4]]

In [228]:
for i in a:
    print (i)

12
3.4
34
cloudxlab
[2.3, 1.4]


In [229]:
a[1]

3.4

In [230]:
print (3 in a)

False


In [231]:
print('cloudx lab' in a)

False


In [232]:
a = [1,2,3,4,5]
for number in a:
   print(number)

1
2
3
4
5


In [240]:
print( a[number])
for number in range(len(a)):
    print( a[number])
    a[number] = a[number] + 1 
    print( a[number])
print (a)

10
6
7
7
8
8
9
9
10
10
11
[7, 8, 9, 10, 11]


In [263]:
a = [1,2,3]    
c = a * 3
print(c)
sum = 0
for i in range(len(c)):
    print ("i is",c[i])
    sum = sum + c[i] 
    print(sum)

[1, 2, 3, 1, 2, 3, 1, 2, 3]
i is 1
1
i is 2
3
i is 3
6
i is 1
7
i is 2
9
i is 3
12
i is 1
13
i is 2
15
i is 3
18


In [271]:
a = [1,2,3,4,5,6,7,8,9]
s = (a[2:5])
sum =0
for i in range(len(s)):
    print ("i is",s[i])
    sum = sum + s[i] 
    print(sum)


i is 3
3
i is 4
7
i is 5
12


In [274]:
a = [1,2,3,4,5,6,7,8,9]
a[2:5] = [7,4,9]
k=a
print(k)
sum = 0
for i in range(len(k)):
    print ("i is",k[i])
    sum = sum + k[i] 
    print(sum)

[1, 2, 7, 4, 9, 6, 7, 8, 9]
i is 1
1
i is 2
3
i is 7
10
i is 4
14
i is 9
23
i is 6
29
i is 7
36
i is 8
44
i is 9
53


In [249]:
print(a[2:5])

[7, 4, 9]


In [285]:
a = [23,12,32,1,2,34,56]
a.append(12)
print(a)
print(a[len(a)-2])

[23, 12, 32, 1, 2, 34, 56, 12]
56


In [286]:
a.extend(a)
sum =0
for i in range(len(a)):
    sum = sum + a[i]
print(sum)

344


In [278]:
print(a)

[23, 12, 32, 1, 2, 34, 56, 12, 23, 12, 32, 1, 2, 34, 56, 12]


In [280]:
a.sort()
print(a)
print(a[2] + a[7])

[1, 1, 2, 2, 12, 12, 12, 12, 23, 23, 32, 32, 34, 34, 56, 56]
14


In [2]:

matrix = [[1, 2, 3, 4], 
    [5, 6, 7, 8],
    [9, 10, 11, 12]]
 
print("Matrix =", matrix)

Matrix = [[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]]


In [7]:
amatrix = [[1, 2, 3, 4], 
    [5, 6, 7, 8]]

In [8]:
print("Matrix =", amatrix)


Matrix = [[1, 2, 3, 4], [5, 6, 7, 8]]


In [10]:
for i in range(len(amatrix)):
    print (amatrix[i])

[1, 2, 3, 4]
[5, 6, 7, 8]


In [14]:
for i in range(len(amatrix)):
    #print (amatrix[i])
    k[0][j] = 0
    for j in range(len(amatrix[i])):
        print (amatrix[i][j])
        k[i][j] = k[i][j] + amatrix[i][j]

NameError: name 'k' is not defined

In [28]:
a=[1,3,2,1]
b=[1,3,4,2,3,4]
#c = a + b

In [29]:
print(c)

[1, 2, 3, 3, 4, 4]


In [32]:
def merge(a,b):
    c = a + b
    c.sort()
    return c
# memory : order of n
# Time Complexity : order n log(n)

In [33]:
merge(a,b)

[1, 1, 1, 2, 2, 3, 3, 3, 4, 4]

In [38]:
def deduplicate1(names):
    resultl = []
    for e in names:
        resultl.append(e)
    return resultl


In [39]:
deduplicate1(["abc","xyz","abc"])

['abc', 'xyz', 'abc']

In [41]:
 names =["sandeep","mohit","sandeep"]
def deduplicate2(names):
    d = {}
    for e in names:
        if e not in d:
            d[e] =True #added to the element
    return list(d.keys())
deduplicate2(names)

['sandeep', 'mohit']

In [1]:
names =["sandeep","mohit","sandeep"]
def deduplicate3(names):
    if len(names) < 2:
        return names
    names.sort()
    result = []
    prev = names[0]
    for name in names[1:]: #o(n)
        if name != prev:
            prev = name
            result.append(name)
    return result

print(deduplicate3(names))

['sandeep']


In [4]:
dir(names)

['__add__',
 '__class__',
 '__contains__',
 '__delattr__',
 '__delitem__',
 '__dir__',
 '__doc__',
 '__eq__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__getitem__',
 '__gt__',
 '__hash__',
 '__iadd__',
 '__imul__',
 '__init__',
 '__init_subclass__',
 '__iter__',
 '__le__',
 '__len__',
 '__lt__',
 '__mul__',
 '__ne__',
 '__new__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__reversed__',
 '__rmul__',
 '__setattr__',
 '__setitem__',
 '__sizeof__',
 '__str__',
 '__subclasshook__',
 'append',
 'clear',
 'copy',
 'count',
 'extend',
 'index',
 'insert',
 'pop',
 'remove',
 'reverse',
 'sort']

In [5]:
d = {'a':10,'b':1}

In [7]:
d.items() # it terurns tuple 

dict_items([('a', 10), ('b', 1)])

In [9]:
a =[]
a.append((1,2))
a

[(1, 2)]

In [2]:
list1 =[12,23,43,[2,4,5],2,4,5]

In [3]:
list1.pop(3)

[2, 4, 5]

In [8]:
list1
sum = 0
for i in range(len(list1)):
    sum = sum + list1[i]
print (sum)
    

89


In [13]:
list2 = ['cloudx', 'lab', 'provides', 'cloud', 'lab']

In [14]:
del list2[1]

In [15]:
print(list2)

['cloudx', 'provides', 'cloud', 'lab']


In [16]:
list2.remove('lab')

In [17]:
list2

['cloudx', 'provides', 'cloud']

In [10]:
list2 = ['cloudx', 'lab', 'provides', 'cloud', 'lab']

In [11]:
del list2[:]

In [13]:
len(list2)

0

In [14]:
s = "CloudxLab"
l = list(s)
print (l)

['C', 'l', 'o', 'u', 'd', 'x', 'L', 'a', 'b']


In [17]:
s = "I am learning Python at CloudxLab"
sp = s.split()
print(sp)

['I', 'am', 'learning', 'Python', 'at', 'CloudxLab']


In [1]:
s = "I am learning Python at CloudxLab"
sp = s.split("am")
print(sp)

['I ', ' learning Python at CloudxLab']


In [2]:
delimiter = "am"    
print(delimiter.join(sp))

I am learning Python at CloudxLab


In [24]:
str1 = ","
str2 = "abc"
len(str2) 
list22 = list(str2)
list22

['a', 'b', 'c']

In [22]:
str1.join(str2)

'a,b,c'

In [122]:
def str_list_func (str1):
    splitchar =' '
    list1 = str1.split(' ')
    end_list = []
    for i in range(len(list1)):
        x = len(list1[i])
        if x > 1:
            print(list1[i])
            list_word = list(list1[i])
        # print(list_word)
            
            swap_1stlist = list_word[0]
            swap_1stlist
            swap_lastlist = list_word[x-1]
            swap_lastlist
            list_word[0] = swap_lastlist
            list_word[x-1] =swap_1stlist
           # print("after swap list is ",list_word)
            delimiter = ''
            return_str = delimiter.join(list_word) 
           # print(return_str)
            end_list.append(return_str)
        else:
            return_str = list1[i]
            end_list.append(return_str)
    print (end_list)
    final_result = splitchar.join(end_list)
    return final_result

In [124]:
str_list_func ('I am learning Python at CloudxLab')

am
learning
Python
at
CloudxLab
['I', 'ma', 'gearninl', 'nythoP', 'ta', 'bloudxLaC']


'I ma gearninl nythoP ta bloudxLaC'

In [54]:
list100 = ['a','b','c']
list100

['a', 'b', 'c']

In [78]:
swap_1stlist = list100[0]
swap_1stlist
swap_lastlist = list100[3-1]
swap_lastlist
list100[0] = swap_lastlist
list100[3-1] =swap_1stlist
list100
delimiter = ''
delimiter.join(list100)

'cba'

In [90]:
end_list =[]
return_str = delimiter.join(list100) 
#print(return_str)
end_list.append(return_str) 
print (end_list)

['cba']


In [89]:
end_list =[]
end_list.append("abc")
end_list.append("aaa")
end_list

['abc', 'aaa']

In [1]:
f = open("file_name.txt")

FileNotFoundError: [Errno 2] No such file or directory: 'file_name.txt'

In [2]:
print("cloud\nx\nlab")

cloud
x
lab


In [1]:
f = open("myfirstfile_copy.txt")

FileNotFoundError: [Errno 2] No such file or directory: 'myfirstfile_copy.txt'

In [38]:
f = open("/cxldata/python_sample_file1")
string_words =f.read()
string_words

FileNotFoundError: [Errno 2] No such file or directory: '/cxldata/python_sample_file1'

In [39]:
with open("/cxldata/python_sample_file") as f:
    #print("read complete")
    s = ""
    for line in f:
       # print(line)
        s = s + line
    print(s)

This is a sample file for testing
for Python course for
learners in CloudxLab.



In [10]:
def file_read_func (path ):
    try:
        
        sp =" "
        ls=[]
        total =0
        with open(path) as f:
            content = f.read()
            print(content)
            content.replace("\n ", "")
            ''.join(content.splitlines())
            
 
           
            for line in content:
                lineofword = line.split(sp)
                #print(lineofword)
               # print(len(lineofword))
                total = total + len(lineofword)
                ls.append(lineofword)
            print(ls)
#             return total
    except:
        return -1
                

In [11]:
file_read_func ("/cxldata/python_sample_file") 

This is a sample file for testing
for Python course for
learners in CloudxLab.

[['T'], ['h'], ['i'], ['s'], ['', ''], ['i'], ['s'], ['', ''], ['a'], ['', ''], ['s'], ['a'], ['m'], ['p'], ['l'], ['e'], ['', ''], ['f'], ['i'], ['l'], ['e'], ['', ''], ['f'], ['o'], ['r'], ['', ''], ['t'], ['e'], ['s'], ['t'], ['i'], ['n'], ['g'], ['\n'], ['f'], ['o'], ['r'], ['', ''], ['P'], ['y'], ['t'], ['h'], ['o'], ['n'], ['', ''], ['c'], ['o'], ['u'], ['r'], ['s'], ['e'], ['', ''], ['f'], ['o'], ['r'], ['\n'], ['l'], ['e'], ['a'], ['r'], ['n'], ['e'], ['r'], ['s'], ['', ''], ['i'], ['n'], ['', ''], ['C'], ['l'], ['o'], ['u'], ['d'], ['x'], ['L'], ['a'], ['b'], ['.'], ['\n']]


In [1]:
check = 0
with open("/cxldata/python_sample_file") as f:
    for line in f:
        if(line.startswith('w')):
            check = check + 1

In [16]:
def startswith (string):
    try:
        
        check =0
        with open(string) as f :
            for line in f:
                print (line)
                if(line.startswith('w')):
                    check = check + 1
                    return check
                else:
                    return 0
    except:
        print("no file present")

In [17]:
startswith ("/cxldata/python_sample_file")

This is a sample file for testing



0

In [22]:
with open("/cxldata/python_sample_file", 'r') as f:
    print(f.read())

This is a sample file for testing
for Python course for
learners in CloudxLab.



In [29]:
with open("cxl.txt", 'w') as f:
    f.write("Python is a scripting language")

In [30]:
with open("cxl.txt", 'a') as f:
    f.write("Python is a scripting language")

In [32]:
with open("clx.txt", 'r') as f:
    print(f.read())

FileNotFoundError: [Errno 2] No such file or directory: 'clx.txt'

In [38]:
with open("python_file_writing.txt", 'w') as f:
    f.write("I am learning Python at CloudxLab.")
    f.close()

In [39]:
with open("python_file_writing.txt") as f:
    print(f.read())

I am learning Python at CloudxLab.


In [7]:
numbers = {"1" : "One", "2" : "Two"}

In [8]:
print(numbers["1"])

One


In [9]:
numbers["3"] = "Three"

In [10]:
numbers

{'1': 'One', '2': 'Two', '3': 'Three'}

In [11]:
my_dictionary = {}
my_dictionary=numbers 
for i in my_dictionary : 
    print (i)

1
2
3


In [13]:
(0, 1, 2000000) < (0, 3, 4)

True

In [2]:
d = dict()

In [3]:
print(d)

{}


In [4]:
d['1 rupee coins'] = 10
d['2 rupees coins'] = 5
d['5 rupees coins'] = 6
d['10 rupees coins'] = 12
print(d)

{'1 rupee coins': 10, '2 rupees coins': 5, '5 rupees coins': 6, '10 rupees coins': 12}


In [7]:
def segm(l, pivot):
    left = 0
    right = len(l) -1
    while True:
        while l[left]< pivot and left < len(l) :
            left += 1
        while l[right] >= pivot and right >= 0:
            right -= 1
        if left < right:
            l[left],l[right]=l[right],l[left]
        else:
            break
    return left

In [9]:
l = [7,12,9,40,8,20,12,17]
pivot = 20
segm(l, pivot)
l

[7, 12, 9, 17, 8, 12, 20, 40]

In [10]:
segm(l, pivot),l

(6, [7, 12, 9, 17, 8, 12, 20, 40])

In [11]:
def segmWithsort(l, pivot):
    left = 0
    right = len(l) -1
    while True:
        while l[left]< pivot and left < len(l) :
            left += 1
        while l[right] >= pivot and right >= 0:
            right -= 1
        if left < right:
            l[left],l[right]=l[right],l[left]
        else:
            break
    return left

In [1]:
def sort1(l):
    if len(l) <= 1:
        return
    
    pivot =l[len(l)//2]
    mid = segmWithsort(l,pivot)

In [2]:
d = { 'one' : 1 , 'two' : 2, 'three' : 3, 'four': 4 }

In [3]:
print(len(d))


4


In [4]:
print('three' in d)

True


In [5]:
print(4 in d)

False


In [6]:
print(5 in d and 2 in d)

False


In [9]:
d= {'1 rupee coins': 10, '2 rupees coins': 5, '5 rupees coins': 6, '10 rupees coins': 12}

In [10]:
print(d['5 rupees coins']+d['10 rupees coins'])

18


In [37]:
d = {"apples" : 2, "bananas" : 3, "carrots" : 12}
print(d.get("apples"))

2


In [34]:
for fruit in d:
    print(fruit)

apples
bananas
carrots


In [17]:
dir(d)

['__class__',
 '__contains__',
 '__delattr__',
 '__delitem__',
 '__dir__',
 '__doc__',
 '__eq__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__getitem__',
 '__gt__',
 '__hash__',
 '__init__',
 '__init_subclass__',
 '__iter__',
 '__le__',
 '__len__',
 '__lt__',
 '__ne__',
 '__new__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__setattr__',
 '__setitem__',
 '__sizeof__',
 '__str__',
 '__subclasshook__',
 'clear',
 'copy',
 'fromkeys',
 'get',
 'items',
 'keys',
 'pop',
 'popitem',
 'setdefault',
 'update',
 'values']

In [25]:
x = d.keys()
print(x)

dict_keys(['apples', 'bananas', 'carrots'])


In [27]:
print(d.items())

dict_items([('apples', 2), ('bananas', 3), ('carrots', 12)])


In [28]:
print(d.values())

dict_values([2, 3, 12])


In [35]:
words = 'the quick brown fox jumps over the lazy dog'
result = {}
#(words)
words = words.split()
for word in words:
   # print (word)
    if word not in result:
       # print(word)
        pervious_sum =1
        result[word] =pervious_sum
        #print(pervious_sum)
    else:
        pervious_sum = result[word]
        print (word)
        result[word] = pervious_sum + 1
print (result.items())
        
##prev_count = result[word]
##result[word]= 2

the
dict_items([('the', 2), ('quick', 1), ('brown', 1), ('fox', 1), ('jumps', 1), ('over', 1), ('lazy', 1), ('dog', 1)])


In [36]:

def dict_func(txt):
    words = txt.lower().split()
    result = {}
    for word in words:
        if word not in result:
            prev_count = 1
            result[word] = prev_count
        else:
            prev_count = result[word]
            print (prev_count)
            result[word] = prev_count + 1
    return result

In [37]:
dict_func('the quick brown fox jumps over the lazy dog')

1


{'the': 2,
 'quick': 1,
 'brown': 1,
 'fox': 1,
 'jumps': 1,
 'over': 1,
 'lazy': 1,
 'dog': 1}

In [41]:
!head /cxldata/big.txt|tr 'A-Z' 'a-z'|sed -E 's/ /\n/g'|sort|uniq -c


      4 
      1 (#15
      1 adventures
      1 all
      1 any
      1 are
      2 arthur
      2 be
      1 before
      2 by
      1 change
      1 changing
      1 check
      2 conan
      2 copyright
      1 country
      2 do
      1 downloading
      1 doyle
      1 doyle)
      1 ebook
      1 ebook.
      1 edit
      1 file.
      1 first
      1 for
      3 gutenberg
      1 header
      1 holmes
      1 in
      1 it.
      2 laws
      2 not
      2 of
      3 or
      1 other
      1 our
      1 over
      1 please
      3 project
      1 redistributing
      1 remove
      1 seen
      1 series
      1 sherlock
      1 should
      2 sir
      1 sure
      6 the
      1 thing
      3 this
      1 to
      1 viewing
      1 when
      1 world.
      1 your


In [45]:
t = (12,323, 'd', [1,23], False)
t

(12, 323, 'd', [1, 23], False)

In [4]:
t = (1)
type(t)

int

In [5]:
t

1

In [6]:
t = tuple()
print(t)

()


In [8]:
t1 = tuple("1,2,3,4,5")
t2 = tuple([1,2,3,4,5])
t3 = tuple((1,2,3,4,5))

In [11]:
len(t3)

5

In [45]:
t = (1,3,5,2,54,34,2,34,5)
print (t[7])
l = len(t)
print(len(t))
print(t[l-2])

34
9
34


In [46]:
t3 = t[1:3] + t2[:]

In [47]:
t3

(3, 5, 5, 2, 54)

In [48]:
sum =0
for i in range(len(t3)):
    print(":",t3[i])
    sum = sum + t3[i]
    print(sum)

: 3
3
: 5
8
: 5
13
: 2
15
: 54
69


In [49]:
t2 = t[2:5]
t2

(5, 2, 54)

In [50]:
sum1 =0
for i in range(len(t2)):
    sum1 = sum1 + t2[i]
print(sum1)

61


In [51]:
print((0, 1, 2) < (0, 3, 4))

True


In [52]:
(0, 1, 2) < (0, 3)

True

In [53]:
l = [(0,23,34), (2,34,23), (1,34,23)]
l.sort()

In [59]:
s=l[2]
print(s)

(2, 34, 23)


In [60]:
sum1 =0
for i in range(len(s)):
    sum1 = sum1 + s[i]
print(sum1)

59


In [ ]:
import re 
hand = open()


In [1]:
!ls -l

total 424
-rw-r--r-- 1 arunavamaiti4453 arunavamaiti4453 113075 Feb 16 13:59 1st_part_Arunava.ipynb
-rw-r--r-- 1 arunavamaiti4453 arunavamaiti4453  30540 Jan 17  2018 Bikes_problem.ipynb
-rw-r--r-- 1 arunavamaiti4453 arunavamaiti4453  33615 Jan 17  2018 Bikes_solution.ipynb
-rw-r--r-- 1 arunavamaiti4453 arunavamaiti4453    581 May 11  2018 cat_vs_noncat_classifier.ipynb
-rw-r--r-- 1 arunavamaiti4453 arunavamaiti4453    581 Sep 14  2020 cat_vs_noncat_numpy.ipynb
-rw-r--r-- 1 arunavamaiti4453 arunavamaiti4453    581 May 11  2018 classify_clothes.ipynb
-rw-r--r-- 1 arunavamaiti4453 arunavamaiti4453    581 Jul 15  2020 classifying_flowers_iris_with_keras.ipynb
-rw-r--r-- 1 arunavamaiti4453 arunavamaiti4453     60 Feb  9 16:02 cxl.txt
-rw-r--r-- 1 arunavamaiti4453 arunavamaiti4453    581 Sep 15  2020 empty_jupyter_file.ipynb
-rw-r--r-- 1 arunavamaiti4453 arunavamaiti4453    581 Dec 28  2017 End_to_end_project.ipynb
-rw-r--r-- 1 arunavamaiti4453 arunavamaiti4453    581 Jul 15  2020 fashion_m

In [2]:
import re 
hand = open 


total 424
-rw-r--r-- 1 arunavamaiti4453 arunavamaiti4453 113075 Feb 16 13:59 1st_part_Arunava.ipynb
-rw-r--r-- 1 arunavamaiti4453 arunavamaiti4453  30540 Jan 17  2018 Bikes_problem.ipynb
-rw-r--r-- 1 arunavamaiti4453 arunavamaiti4453  33615 Jan 17  2018 Bikes_solution.ipynb
-rw-r--r-- 1 arunavamaiti4453 arunavamaiti4453    581 May 11  2018 cat_vs_noncat_classifier.ipynb
-rw-r--r-- 1 arunavamaiti4453 arunavamaiti4453    581 Sep 14  2020 cat_vs_noncat_numpy.ipynb
-rw-r--r-- 1 arunavamaiti4453 arunavamaiti4453    581 May 11  2018 classify_clothes.ipynb
-rw-r--r-- 1 arunavamaiti4453 arunavamaiti4453    581 Jul 15  2020 classifying_flowers_iris_with_keras.ipynb
-rw-r--r-- 1 arunavamaiti4453 arunavamaiti4453     60 Feb  9 16:02 cxl.txt
-rw-r--r-- 1 arunavamaiti4453 arunavamaiti4453    581 Sep 15  2020 empty_jupyter_file.ipynb
-rw-r--r-- 1 arunavamaiti4453 arunavamaiti4453    581 Dec 28  2017 End_to_end_project.ipynb
-rw-r--r-- 1 arunavamaiti4453 arunavamaiti4453    581 Jul 15  2020 fashion_m

In [63]:
import re 
x = "My 2 favorite numbers are 19 and 42"
a ="From stephen.marquard@uct.ac.za Sat Jan 5 09:14:16 2008"
y = re.findall("[0-9]+",x)
z = re.findall("\S+@\S+",a)

In [65]:
print(z)

['stephen.marquard@uct.ac.za']


In [ ]:
words = lise.split()

In [6]:
arr = [(1,"Abhinav"),(3,"Sandeep"),(2,"shivanshu"),(4,"Abhishek")]
arr.sort()

In [9]:
arr

[(1, 'Abhinav'), (2, 'shivanshu'), (3, 'Sandeep'), (4, 'Abhishek')]

In [10]:
new_arr = []
for f,s in arr:
    new_arr.append(f,s)

TypeError: append() takes exactly one argument (2 given)

In [1]:
import socket
import sys

hostname = "www.bing.com"

try:
    s = socket.socket(socket.AF_INET, socket.SOCK_STREAM)
    print ("Socket successfully created here")
except socket.error as err:
    print ("Socket creation failed here with error %s" %(err))

# default port for socket
port = 80

try:
    host_ip = socket.gethostbyname(hostname)
except socket.gaierror:
    print ("Error resolving the host")
    sys.exit()

# connecting to the server
s.connect((host_ip, port))

print (f"Socket successfully connected to {hostname}")

Socket successfully created here
Socket successfully connected to www.bing.com


In [ ]:
#server side program
import socket
# create a socket object
s = socket.socket()
print ("Socket successfully created")
# choose any random available port
port = 4042

# Next bind to the port
# empty string makes listen from all computers in the network
s.bind(('', port))
print ("socket binded to %s" %(port))
# start listening
s.listen(5)
print ("socket started listening")

# a forever loop until we interrupt it or
# an error occurs
counter = 0
while counter < 5:
    # Keep establishing connection with clients
    c, addr = s.accept()
    print ('Got a connection from', addr )
    counter+= 1
    # send a message to the client. encoding to send byte type.
    c.send('We listened to you'.encode())
    # Close the connection with the client
    c.close()
    # Breaking once connection closed

Socket successfully created
socket binded to 4042
socket started listening


In [ ]:
class Vehicle:
    #dunder
    def __init__(self, color, make, model="Good"):
        self.color = color
        self.make = make
        self.model = model
        self.speed = 0
        #self.drag = 0

    def __repr__(self):
        return "My vehicle is:" + self.color + ":" + self.make + ":" + str(self.speed)

    def run(self, speed):
        self.speed = speed

veh1 = Vehicle("Red", "Toyota", "Corrola")
print(veh1)
print(veh1.color)
print(veh1.make)
print(veh1.model)
veh1.run(100)
print(veh1)

myvehs = [
    Vehicle("Red", "Toyota1", "Corrola1"),
    Vehicle("Reds", "Toyota2", "Corrola2"),
    Vehicle("Redd", "Toyota3", "Corrola3"),
    Vehicle("Redd", "Toyota4", "Corrola4")
]

for veh in myvehs:
    print(veh)

class Car(Vehicle):
    drag = 0
    def do_drag(self, drag):
        self.drag = drag

    def __repr__(self):
        return "My car is:" + self.color + ":" + self.make + ":" + " Drag: " + str(self.drag)

car = Car("Red", "Toyota", "Corrola")
print(car)
car.do_drag(90)
print(car)

class CarSports(Car, Vehicle):
    fly = 0
    def do_fly(self, fly):
        self.fly = fly

    def __repr__(self):
        return "My car is:" + self.color + ":" + self.make + ":" + " Drag: " + str(self.drag) \
        + " Fly: " + str(self.fly)

carsports1 = CarSports("Red", "Toyota", "Corrola")
print(carsports1)
carsports1.do_fly(90)
print(carsports1)

In [ ]:
lambda arguments : expression

In [7]:
array1 = [[1,2],[2,4],[3,3]]
array2 =[]
for i in range(len(array1)):
    print(array1[i])
    for j in range(len(array1[i]))
        print(array1[i][j])

SyntaxError: invalid syntax (<ipython-input-7-fe9fc780f95c>, line 5)

In [ ]:
def gaussian_elimination(A, b):
    n = len(A)

    # Forward elimination
    for i in range(n):
        # Partial pivoting
        max_index = i
        for j in range(i + 1, n):
            if abs(A[j][i]) > abs(A[max_index][i]):
                max_index = j
        A[i], A[max_index] = A[max_index], A[i]
        b[i], b[max_index] = b[max_index], b[i]

        # Make all entries below A[i][i] zero
        for j in range(i + 1, n):
            factor = A[j][i] / A[i][i]
            for k in range(i, n):
                A[j][k] -= factor * A[i][k]
            b[j] -= factor * b[i]

    # Back substitution
    x = [0] * n
    for i in range(n - 1, -1, -1):
        x[i] = b[i] / A[i][i]
        for j in range(i):
            b[j] -= A[j][i] * x[i]

    return x

# Example usage:
A = [[2, 3, -4], [1, -1, 1], [3, 6, -8]]  # Coefficient matrix
b = [10, 2, 26]                           # Constants vector

solution = gaussian_elimination(A, b)
print("Solution:", solution)

In [31]:
A = [[2, 3, -4], [1, -1, 1], [3, 6, -8]]  # Coefficient matrix
b = [10, 2, 26]                           # Constants vector
n = len(A)
print(A,"---->",n)

[[2, 3, -4], [1, -1, 1], [3, 6, -8]] ----> 3


In [32]:
# Forward elimination
for i in range(n):
    # Partial pivoting
        max_index = i #0
        print(A[max_index]) #0
        for j in range(i+1 , n):
            
            if abs(A[j][i]) > abs(A[max_index][i]):
                print("A[j][i]:-->",A[j][i])
                print("A[max_index][i]:-->",A[max_index][i])
                max_index = j
                print("j-->",j)
                A[i], A[max_index] = A[max_index], A[i]
                b[i], b[max_index] = b[max_index], b[i]
                print (A[i], A[max_index])
                print (b[i], b[max_index])
                        # Make all entries below A[i][i] zero
        for j in range(i + 1, n):
            factor = A[j][i] / A[i][i]
            for k in range(i, n):
                A[j][k] -= factor * A[i][k]
            b[j] -= factor * b[i]
            print(b[j])
    

[2, 3, -4]
A[j][i]:--> 3
A[max_index][i]:--> 2
j--> 2
[3, 6, -8] [2, 3, -4]
26 10
-6.666666666666666
-7.333333333333332
[0.0, -3.0, 3.6666666666666665]
-5.111111111111111
[0.0, 0.0, 0.11111111111111094]


5