In [6]:
import numpy as np

In [5]:
my_list = []

In [8]:
my_list = [50, 12, 67, 23]
my_list

[50, 12, 67, 23]

In [15]:
print(my_list)

[50, 12, 67, 23]


In [16]:
my_list_array = np.array(my_list)
my_list_array

array([50, 12, 67, 23])

In [14]:
print(my_list_array)

[50 12 67 23]


In [17]:
my_tup = (88, 17, 45, 76)

In [19]:
my_tup_arr = np.array(my_tup)
my_tup_arr

array([88, 17, 45, 76])

In [20]:
print(my_tup_arr)

[88 17 45 76]


In [21]:
%timeit

In [22]:
sample_list = [1,2,3]

In [26]:
list_array = np.array(sample_list)
list_array

array([1, 2, 3])

In [25]:
print(list_array )

[1 2 3]


In [27]:
tup = (1,2,3)

In [28]:
my_tup_array = np.array(tup)

In [29]:
print(my_tup_array)

[1 2 3]
